### ISSUE TITLE
Контент в отзывах

### ISSUE THREAD

**Issue by igosheva** [bermitti/burgers#6]
comments-list__img - про это мы с тобой говорили, картинку лучше положить на фон comments-list__item.
При наведении на картинку должен появляться контент (comments-list__description), к которого есть на фоне темный фон с прозрачностью (background-color: rgba(20, 20, 20, 0.7);). Также контент comments-list__description должен тянуться на 100% высоты и 100% ширины родителя.

**Comment by bermitti** [comment]
исправленно
