### ISSUE TITLE
Секция слайдера

### ISSUE THREAD

**Issue by igosheva** [bermitti/burgers#8]
Добавь ТОЛЬКО один элемент секции, выравни все по пиксель перфекту, и только потом добавляй другие элементы слайдера и делай динамику. Сейчас вот что происходит если оставляешь один элемент слайдера(burgers-slider__item) http://joxi.ru/BA0WZoauBvW992
В домашке так и написано - верстаем пока только один элемент слайдера https://drive.google.com/file/d/0B17mudWh9TdjdWlqT0xHUjN6c3c/view

**Comment by igosheva** [comment]
ingredients__dropdown - должна появляться только по ховеру на ingredients

**Comment by igosheva** [comment]
ingredients__table - добавить width: 100%;

**Comment by igosheva** [comment]
ingredients__icon-text - не применился шрифт

**Comment by igosheva** [comment]
Оберни ingredients__icon и ingredients__icon-text в отдельный тег и ему задай цвет фона, радиус и т.д.. Именно на ховер по этому элементу должен появляться ingredients__dropdown
У этого нового элемента должно быть скругление 5px по бокам и он должен лежать на одном уровне с ingredients__dropdown

**Comment by igosheva** [comment]
burgers-slider__item - у этого элемента должна быть максимальная ширина)

**Comment by igosheva** [comment]
burgers-slider__right-buy - кнопка по макету должна быть больше

**Comment by igosheva** [comment]
burgers-slider__right-text - межстрочное расстояние по макету больше

**Comment by bermitti** [comment]
Оберни ingredients__icon и ingredients__icon-text в отдельный тег и ему задай цвет фона, радиус и т.д.. Именно на ховер по этому элементу должен появляться ingredients__dropdown
У этого нового элемента должно быть скругление 5px по бокам и он должен лежать на одном уровне с ingredients__dropdown   -  сделал       &:hover{
        .ingredients__dropdown{
            display: block;
        }
    }почему тек нельзя?
